language: node_js
node_js:
  - "0.10"
  - "0.12"
env:
  - NODE_ENV=travis
services:
  - mongodb
before_install:
  - gem update --system
  - gem install sass --version "=3.3.7"
  - npm i nsp -g
after_script:
  - nsp audit-package
